package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATEGORY".
 */
public class Category {

    private Integer id;
    private String categorycol;
    private String categorycol1;
    private java.util.Date categorycol2;
    private Byte categorycol3;
    private String categorycol4;
    private String categorycol5;
    private Byte categorycol6;
    private Byte categorycol7;
    private Byte categorycol8;
    private Byte categorycol9;
    private String categorycol10;
    private java.util.Date categorycol11;
    private String categorycol12;
    private String categorycol13;
    private String categorycol14;
    private String categorycol15;
    private String categorycol16;
    private String categorycol17;
    private String categorycol18;
    private String categorycol19;
    private String categorycol20;
    private String categorycol21;
    private String categorycol22;

    public Category() {
    }

    public Category(Integer id, String categorycol, String categorycol1, java.util.Date categorycol2, Byte categorycol3, String categorycol4, String categorycol5, Byte categorycol6, Byte categorycol7, Byte categorycol8, Byte categorycol9, String categorycol10, java.util.Date categorycol11, String categorycol12, String categorycol13, String categorycol14, String categorycol15, String categorycol16, String categorycol17, String categorycol18, String categorycol19, String categorycol20, String categorycol21, String categorycol22) {
        this.id = id;
        this.categorycol = categorycol;
        this.categorycol1 = categorycol1;
        this.categorycol2 = categorycol2;
        this.categorycol3 = categorycol3;
        this.categorycol4 = categorycol4;
        this.categorycol5 = categorycol5;
        this.categorycol6 = categorycol6;
        this.categorycol7 = categorycol7;
        this.categorycol8 = categorycol8;
        this.categorycol9 = categorycol9;
        this.categorycol10 = categorycol10;
        this.categorycol11 = categorycol11;
        this.categorycol12 = categorycol12;
        this.categorycol13 = categorycol13;
        this.categorycol14 = categorycol14;
        this.categorycol15 = categorycol15;
        this.categorycol16 = categorycol16;
        this.categorycol17 = categorycol17;
        this.categorycol18 = categorycol18;
        this.categorycol19 = categorycol19;
        this.categorycol20 = categorycol20;
        this.categorycol21 = categorycol21;
        this.categorycol22 = categorycol22;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCategorycol() {
        return categorycol;
    }

    public void setCategorycol(String categorycol) {
        this.categorycol = categorycol;
    }

    public String getCategorycol1() {
        return categorycol1;
    }

    public void setCategorycol1(String categorycol1) {
        this.categorycol1 = categorycol1;
    }

    public java.util.Date getCategorycol2() {
        return categorycol2;
    }

    public void setCategorycol2(java.util.Date categorycol2) {
        this.categorycol2 = categorycol2;
    }

    public Byte getCategorycol3() {
        return categorycol3;
    }

    public void setCategorycol3(Byte categorycol3) {
        this.categorycol3 = categorycol3;
    }

    public String getCategorycol4() {
        return categorycol4;
    }

    public void setCategorycol4(String categorycol4) {
        this.categorycol4 = categorycol4;
    }

    public String getCategorycol5() {
        return categorycol5;
    }

    public void setCategorycol5(String categorycol5) {
        this.categorycol5 = categorycol5;
    }

    public Byte getCategorycol6() {
        return categorycol6;
    }

    public void setCategorycol6(Byte categorycol6) {
        this.categorycol6 = categorycol6;
    }

    public Byte getCategorycol7() {
        return categorycol7;
    }

    public void setCategorycol7(Byte categorycol7) {
        this.categorycol7 = categorycol7;
    }

    public Byte getCategorycol8() {
        return categorycol8;
    }

    public void setCategorycol8(Byte categorycol8) {
        this.categorycol8 = categorycol8;
    }

    public Byte getCategorycol9() {
        return categorycol9;
    }

    public void setCategorycol9(Byte categorycol9) {
        this.categorycol9 = categorycol9;
    }

    public String getCategorycol10() {
        return categorycol10;
    }

    public void setCategorycol10(String categorycol10) {
        this.categorycol10 = categorycol10;
    }

    public java.util.Date getCategorycol11() {
        return categorycol11;
    }

    public void setCategorycol11(java.util.Date categorycol11) {
        this.categorycol11 = categorycol11;
    }

    public String getCategorycol12() {
        return categorycol12;
    }

    public void setCategorycol12(String categorycol12) {
        this.categorycol12 = categorycol12;
    }

    public String getCategorycol13() {
        return categorycol13;
    }

    public void setCategorycol13(String categorycol13) {
        this.categorycol13 = categorycol13;
    }

    public String getCategorycol14() {
        return categorycol14;
    }

    public void setCategorycol14(String categorycol14) {
        this.categorycol14 = categorycol14;
    }

    public String getCategorycol15() {
        return categorycol15;
    }

    public void setCategorycol15(String categorycol15) {
        this.categorycol15 = categorycol15;
    }

    public String getCategorycol16() {
        return categorycol16;
    }

    public void setCategorycol16(String categorycol16) {
        this.categorycol16 = categorycol16;
    }

    public String getCategorycol17() {
        return categorycol17;
    }

    public void setCategorycol17(String categorycol17) {
        this.categorycol17 = categorycol17;
    }

    public String getCategorycol18() {
        return categorycol18;
    }

    public void setCategorycol18(String categorycol18) {
        this.categorycol18 = categorycol18;
    }

    public String getCategorycol19() {
        return categorycol19;
    }

    public void setCategorycol19(String categorycol19) {
        this.categorycol19 = categorycol19;
    }

    public String getCategorycol20() {
        return categorycol20;
    }

    public void setCategorycol20(String categorycol20) {
        this.categorycol20 = categorycol20;
    }

    public String getCategorycol21() {
        return categorycol21;
    }

    public void setCategorycol21(String categorycol21) {
        this.categorycol21 = categorycol21;
    }

    public String getCategorycol22() {
        return categorycol22;
    }

    public void setCategorycol22(String categorycol22) {
        this.categorycol22 = categorycol22;
    }

}
