package de.greenrobot.daoexample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;



import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daoexample.AutoTag;

import de.greenrobot.daoexample.AutoTagDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig autoTagDaoConfig;

    private final AutoTagDao autoTagDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        autoTagDaoConfig = daoConfigMap.get(AutoTagDao.class).clone();
        autoTagDaoConfig.initIdentityScope(type);

        autoTagDao = new AutoTagDao(autoTagDaoConfig, this);

        registerDao(AutoTag.class, autoTagDao);
    }
    
    public void clear() {
        autoTagDaoConfig.getIdentityScope().clear();
    }

    public AutoTagDao getAutoTagDao() {
        return autoTagDao;
    }

}
