package de.greenrobot.daoexample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daoexample.Group_user;
import de.greenrobot.daoexample.User;
import de.greenrobot.daoexample.Group;
import de.greenrobot.daoexample.Category;

import de.greenrobot.daoexample.Group_userDao;
import de.greenrobot.daoexample.UserDao;
import de.greenrobot.daoexample.GroupDao;
import de.greenrobot.daoexample.CategoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig group_userDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig groupDaoConfig;
    private final DaoConfig categoryDaoConfig;

    private final Group_userDao group_userDao;
    private final UserDao userDao;
    private final GroupDao groupDao;
    private final CategoryDao categoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        group_userDaoConfig = daoConfigMap.get(Group_userDao.class).clone();
        group_userDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        group_userDao = new Group_userDao(group_userDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        groupDao = new GroupDao(groupDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);

        registerDao(Group_user.class, group_userDao);
        registerDao(User.class, userDao);
        registerDao(Group.class, groupDao);
        registerDao(Category.class, categoryDao);
    }
    
    public void clear() {
        group_userDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        groupDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
    }

    public Group_userDao getGroup_userDao() {
        return group_userDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

}
