package de.greenrobot.daoexample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daoexample.group_user;
import de.greenrobot.daoexample.user;
import de.greenrobot.daoexample.group;

import de.greenrobot.daoexample.group_userDao;
import de.greenrobot.daoexample.userDao;
import de.greenrobot.daoexample.groupDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig group_userDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig groupDaoConfig;

    private final group_userDao group_userDao;
    private final userDao userDao;
    private final groupDao groupDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        group_userDaoConfig = daoConfigMap.get(group_userDao.class).clone();
        group_userDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(userDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        groupDaoConfig = daoConfigMap.get(groupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        group_userDao = new group_userDao(group_userDaoConfig, this);
        userDao = new userDao(userDaoConfig, this);
        groupDao = new groupDao(groupDaoConfig, this);

        registerDao(group_user.class, group_userDao);
        registerDao(user.class, userDao);
        registerDao(group.class, groupDao);
    }
    
    public void clear() {
        group_userDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        groupDaoConfig.getIdentityScope().clear();
    }

    public group_userDao getGroup_userDao() {
        return group_userDao;
    }

    public userDao getUserDao() {
        return userDao;
    }

    public groupDao getGroupDao() {
        return groupDao;
    }

}
